---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# VIBMDS

<!-- badges: start -->
<!-- badges: end -->

Variational Inference Bayesian Multidimensional Scaling (VIBMDS) is a variational inference algorithm applied to the Bayesian Multidimensional Scaling model. 

## Installation

You can install the development version of VIBMDS from [GitHub](https://github.com/) with:

``` r
# install.packages("pak")
pak::pak("SamMorrissette/VIBMDS")
```

## Iris Example

A simple example showing how to apply VIBMDS to the Iris dataset for dimension reduction. 

```{r example}
library(VIBMDS)
library(torch)

device <- torch_device("cpu")
```

```{r}
iris_dist <- as.matrix(dist(iris[,1:4]))

# Uninformative priors:
prior_params <- list(scale_lambda = torch_tensor(25.0, device = device),
                     scale_sigma = torch_tensor(25.0, device = device))

# Run VIBMDS
results <- VIBMDS::vi_bmds(iris_dist, 
                           p = 2, 
                           prior_params = prior_params,
                           B = 1000, S = 10, max_iter = 5000, 
                           device = device)
```
```{r}
# Generate object configurations from the variational approximation
var_samples <- generate_z(results, 1000) 
config <- as.matrix(var_samples$x$mean(dim = 1))
```
```{r}
# Plot the final configuration
plot(config, col = iris$Species, main = "Object configuration",
     xlab = "Dimension 1", ylab = "Dimension 2")
```

